version: '3.1'

services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: fxsignal
      MYSQL_USER: fxuser
      MYSQL_PASSWORD: secret
