-- AlterTable
ALTER TABLE `Price` ADD COLUMN `d1_histogram` DECIMAL(11, 8) NOT NULL DEFAULT 0,
    ADD COLUMN `d1_macd` DECIMAL(11, 8) NOT NULL DEFAULT 0,
    ADD COLUMN `d1_signal` DECIMAL(11, 8) NOT NULL DEFAULT 0,
    ADD COLUMN `h4_histogram` DECIMAL(11, 8) NOT NULL DEFAULT 0,
    ADD COLUMN `h4_macd` DECIMAL(11, 8) NOT NULL DEFAULT 0,
    ADD COLUMN `h4_signal` DECIMAL(11, 8) NOT NULL DEFAULT 0;
